In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('data.txt')

In [3]:
df

    mdb001 G CIRC B 535 425 197
0    mdb002 G CIRC B 522 280 69
1                mdb003 D NORM
2                mdb004 D NORM
3    mdb005 F CIRC B 477 133 30
4    mdb005 F CIRC B 500 168 26
5                mdb006 F NORM
6                mdb007 G NORM
7                mdb008 G NORM
8                mdb009 F NORM
9    mdb010 F CIRC B 525 425 33
10               mdb011 F NORM
11   mdb012 F CIRC B 471 458 40
12   mdb013 G MISC B 667 365 31
13               mdb014 G NORM
14   mdb015 G CIRC B 595 864 68
15               mdb016 G NORM
16   mdb017 G CIRC B 547 573 48
17               mdb018 G NORM
18   mdb019 G CIRC B 653 477 49
19               mdb020 G NORM
20   mdb021 G CIRC B 493 125 49
21               mdb022 G NORM
22   mdb023 G CIRC M 538 681 29
23               mdb024 G NORM
24   mdb025 F CIRC B 674 443 79
25               mdb026 F NORM
26               mdb027 F NORM
27   mdb028 F CIRC M 338 314 56
28               mdb029 G NORM
29   mdb030 G MISC B 322 676 43
..                          ...
299              mdb293 F NORM
300              mdb294 F NORM
301              mdb295 D NORM
302              mdb296 D NORM
303              mdb297 F NORM
304              mdb298 F NORM
305              mdb299 F NORM
306              mdb300 F NORM
307              mdb301 F NORM
308              mdb302 F NORM
309              mdb303 F NORM
310              mdb304 F NORM
311              mdb305 F NORM
312              mdb306 F NORM
313              mdb307 F NORM
314              mdb308 F NORM
315              mdb309 F NORM
316              mdb310 F NORM
317              mdb311 F NORM
318  mdb312 F MISC B 240 263 20
319              mdb313 F NORM
320  mdb314 F MISC B 518 191 39
321  mdb315 D CIRC B 516 447 93
322              mdb316 D NORM
323              mdb317 D NORM
324              mdb318 D NORM
325              mdb319 D NORM
326              mdb320 D NORM
327              mdb321 D NORM
328              mdb322 D NORM

[329 rows x 1 columns]